apiVersion: v1
items:
- apiVersion: v1
  data:
    hazelcast.xml: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                    xmlns="http://www.hazelcast.com/schema/config"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <network>
          <join>
            <multicast enabled="false"/>
            <kubernetes enabled="true">
              <namespace>cache-api</namespace>
              <service-name>hazelcast-embedded-api</service-name>
              <kubernetes-api-retries>5</kubernetes-api-retries>
              <kubernetes-master>https://kubernetes.default.svc</kubernetes-master>
            </kubernetes>
          </join>
        </network>
      </hazelcast>
  kind: ConfigMap
  metadata:
    name: hazelcast-configuration-api
    namespace: cache-api
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
