apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hazelcast-embedded-api
  name: hazelcast-embedded-api
spec:
  ports:
  - name: hzport
    port: 5071
    protocol: TCP
    targetPort: 5071
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hazelcast-embedded-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
