apiVersion: v1
kind: Service
metadata:
  name: hazelcast-dns
spec:
  clusterIP: None
  ports:
  - name: hazelcast
    port: 5701
    protocol: TCP
    targetPort: 5701
  selector:
    app: hazelcast-embedded
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
