apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-cache-api
  namespace: cache-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-cache-api
subjects:
- kind: ServiceAccount
  name: hazelcast-cache
  namespace: cache-api